sqlite_settings: &sqlite_settings
  adapter: sqlite3
  pool:    5
  timeout: 5000

postgres_settings: &postgres_settings
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development: &development
  <<: *sqlite_settings
  host: localhost  #if the server runs in same server
  port: 5432
  encoding: unicode
  database: curate_development
  username: rails_user
  password:

development_remote_purl_database:
  <<: *development

test: &test
  <<: *development
  database: curate_test

test_remote_purl_database:
  <<: *test

ci: &ci
  <<: *test

ci_remote_purl_database:
  <<: *ci