default: &DEFAULT
  jetty_port: 8983
  jetty_home: <%= Rails.root.join('jetty') %>
  startup_wait: 75
  java_opts:
    - "-XX:+CMSPermGenSweepingEnabled"
    - "-XX:+CMSClassUnloadingEnabled"
    - "-XX:PermSize=64M"
    - "-XX:MaxPermSize=128M"
  quiet: true
test: &TEST
  <<: *DEFAULT
  jetty_home: <%= Rails.root.join('jetty') %>
